name: aid_brazil
description: A new Flutter project.

publish_to: "none"

version: 0.0.7

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_mobile_ads: ^1.3.0
  intl: ^0.17.0
  rxdart: ^0.27.4
  overlay_support: ^2.0.1
  extended_masked_text: ^2.3.1
  cpf_cnpj_validator: ^2.0.0
  http: ^0.13.5
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.0.3
  google_fonts: ^3.0.1
  share_plus: ^4.0.10
  url_launcher: ^6.1.5
  connectivity_plus: ^2.3.6
  flutter_local_notifications: ^9.7.0
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  firebase_remote_config: ^2.0.19
  webfeed: ^0.7.0 
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  flutter_fgbg: ^0.2.0
  cached_network_image: ^3.2.2
  flutter_native_splash: ^2.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher/launcher.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#ffffff"
  image: assets/launcher/splash.png
  android_12:
    image: assets/launcher/splash.png
    icon_background_color: "#ffffff"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/launcher/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/rubik/Rubik-BlackItalic.ttf
          weight: 900
          style: italic

        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/rubik/Rubik-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/rubik/Rubik-LightItalic.ttf
          weight: 300
          style: italic

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
